/* lineno 164 ctr 0 source ¡ uni ¡ ace xn--7a nv8 NV8 line B;	¡;	;	xn--7a;	NV8
 */
{ "¡", "xn--7a", -1 },
/* lineno 269 ctr 1 source ☕ uni ☕ ace xn--53h nv8 NV8 line B;	☕;	;	xn--53h;	NV8
 */
{ "☕", "xn--53h", -1 },
/* lineno 533 ctr 2 source xn--ss-1ju. uni ss" "\xe2\x83\x98" ". ace xn--ss-1ju. nv8 NV8 line B;	xn--ss-1ju.;	ss\u20D8.;	xn--ss-1ju.;	NV8	#	ss⃘.
 */
{ "ss" "\xe2\x83\x98" ".", "xn--ss-1ju.", -1 },
/* lineno 1024 ctr 3 source xn--56e26q0321avb7g.xn--h4h uni 🏨ᠣ" "\xe1\xaf\xb1" "" "\xed\xa0\x84" "" "\xed\xb7\x80" ".☠ ace xn--56e26q0321avb7g.xn--h4h nv8 NV8 line B;	xn--56e26q0321avb7g.xn--h4h;	🏨ᠣ\u1BF1\uD804\uDDC0.☠;	xn--56e26q0321avb7g.xn--h4h;	NV8	#	🏨ᠣᯱ𑇀.☠
 */
{ "🏨ᠣ" "\xe1\xaf\xb1" "" "\xed\xa0\x84" "" "\xed\xb7\x80" ".☠", "xn--56e26q0321avb7g.xn--h4h", -1 },
/* lineno 2085 ctr 4 source xn--1-yn1bw30gq07b.6.xn--7xh uni ꡖ目姶1.6.╅ ace xn--1-yn1bw30gq07b.6.xn--7xh nv8 NV8 line B;	xn--1-yn1bw30gq07b.6.xn--7xh;	ꡖ目姶1.6.╅;	xn--1-yn1bw30gq07b.6.xn--7xh;	NV8
 */
{ "ꡖ目姶1.6.╅", "xn--1-yn1bw30gq07b.6.xn--7xh", -1 },
/* lineno 2916 ctr 5 source xn--16f130edj8dsszv.xn--e5h11w uni ⴜ𤮹" "\xe1\xb3\xa8" "舛.ⴏ♀ ace xn--16f130edj8dsszv.xn--e5h11w nv8 NV8 line B;	xn--16f130edj8dsszv.xn--e5h11w;	ⴜ𤮹\u1CE8舛.ⴏ♀;	xn--16f130edj8dsszv.xn--e5h11w;	NV8	#	ⴜ𤮹᳨舛.ⴏ♀
 */
{ "ⴜ𤮹" "\xe1\xb3\xa8" "舛.ⴏ♀", "xn--16f130edj8dsszv.xn--e5h11w", -1 },
/* lineno 3486 ctr 6 source xn--88e.xn--pkj uni ᡬ.⳾ ace xn--88e.xn--pkj nv8 NV8 line B;	xn--88e.xn--pkj;	ᡬ.⳾;	xn--88e.xn--pkj;	NV8
 */
{ "ᡬ.⳾", "xn--88e.xn--pkj", -1 },
/* lineno 3631 ctr 7 source 𝟱。🜎ᢧ uni 5.🜎ᢧ ace 5.xn--xbf5506v nv8 NV8 line B;	𝟱。🜎ᢧ;	5.🜎ᢧ;	5.xn--xbf5506v;	NV8
 */
{ "5.🜎ᢧ", "5.xn--xbf5506v", -1 },
/* lineno 4449 ctr 8 source 🁪.ⴂᠺ\u17143 uni 🁪.ⴂᠺ" "\xe1\x9c\x94" "3 ace xn--jw7h.xn--3-kpjx0e812d nv8 NV8 line B;	🁪.ⴂᠺ\u17143;	;	xn--jw7h.xn--3-kpjx0e812d;	NV8	#	🁪.ⴂᠺ᜔3
 */
{ "🁪.ⴂᠺ" "\xe1\x9c\x94" "3", "xn--jw7h.xn--3-kpjx0e812d", -1 },
/* lineno 4787 ctr 9 source xn--2gb0b.xn--zve uni " "\xd8\xb7" "" "\xd9\x89" ".᚜ ace xn--2gb0b.xn--zve nv8 NV8 line B;	xn--2gb0b.xn--zve;	\u0637\u0649.᚜;	xn--2gb0b.xn--zve;	NV8	#	طى.᚜
 */
{ "" "\xd8\xb7" "" "\xd9\x89" ".᚜", "xn--2gb0b.xn--zve", -1 },
